name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo tarpaulin
    - name: Render image
      run: |
        mkdir out 
        cargo run --release
    - name: upload last render
      uses: actions/upload-artifact@v3
      with:
        name: renders
        path: out/
